In [34]:
import torch
from helper import synthetic_data
from torch.utils.data import DataLoader
from LinearRegressor import LinearRegressor

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [35]:
# Generate Testing Data
num_inputs = 2
num_examples = 1000
val_examples = 100

true_w = torch.Tensor([2, -3.4])
true_b = 4.2

train_features, train_labels = synthetic_data(true_w, true_b, num_examples)
train_labels = train_labels.reshape(-1, 1)

val_features, val_labels = synthetic_data(true_w, true_b, val_examples)
val_labels = val_labels.reshape(-1, 1)

In [36]:
batch_size = 10
dataset = DataLoader(
    list(zip(train_features, train_labels)), 
    batch_size=batch_size, 
    shuffle=True
)

In [37]:
lrNet = LinearRegressor(num_inputs, True)
lrNet.initialize()
lrNet.train(dataset, epochs=5)

[epoch 1, batch 20] loss: 14.26408256292343
[epoch 1, batch 40] loss: 1.0169611148536206
[epoch 1, batch 60] loss: 0.08830916071310639
[epoch 1, batch 80] loss: 0.007786008226685226
[epoch 1, batch 100] loss: 0.0007235627883346752
[epoch 2, batch 20] loss: 0.0001661675651121186
[epoch 2, batch 40] loss: 0.00011112000884168083
[epoch 2, batch 60] loss: 9.202884266414912e-05
[epoch 2, batch 80] loss: 0.00010175279439863515
[epoch 2, batch 100] loss: 0.0001116107590860338
[epoch 3, batch 20] loss: 9.230825066879334e-05
[epoch 3, batch 40] loss: 9.692205539977295e-05
[epoch 3, batch 60] loss: 0.00010474485497979913
[epoch 3, batch 80] loss: 0.00010102117075803108
[epoch 3, batch 100] loss: 0.00012542888434836642
[epoch 4, batch 20] loss: 9.307851455560012e-05
[epoch 4, batch 40] loss: 0.00010205353692072094
[epoch 4, batch 60] loss: 0.00011490196175145684
[epoch 4, batch 80] loss: 0.00010324705053790239
[epoch 4, batch 100] loss: 0.0001076043432476581
[epoch 5, batch 20] loss: 0.0001072326

LinearRegressor(
  (fc1): Linear(in_features=2, out_features=1, bias=True)
  (criterion): MSELoss()
)

In [38]:
print(f"Training Loss: {lrNet.criterion(lrNet(train_features), train_labels).data:.5f}\n")
print(f"Validation Loss: {lrNet.criterion(lrNet(val_features), val_labels).data:.5f}\n")

print(f"Model Weights: \n{lrNet[0].weight.data}")
print(f"Model Bias: \n{lrNet[0].bias.data}\n")

print(f"True Weights: \n{true_w}")
print(f"True Bias: \n{true_b}\n")

Training Loss: 0.00010

Validation Loss: 0.00011

Model Weights: 
tensor([[ 1.9992, -3.4003]])
Model Bias: 
tensor([4.1998])

True Weights: 
tensor([ 2.0000, -3.4000])
True Bias: 
4.2

