In [12]:
import torch
from helper import synthetic_data
from torch.utils.data import DataLoader
from LinearRegressor import LinearRegressor

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
# Generate Testing Data
num_inputs = 2
num_examples = 1000
val_examples = 100

true_w = torch.Tensor([2, -3.4])
true_b = 4.2

train_features, train_labels = synthetic_data(true_w, true_b, num_examples)
train_labels = train_labels.reshape(-1, 1)

val_features, val_labels = synthetic_data(true_w, true_b, val_examples)
val_labels = val_labels.reshape(-1, 1)

In [14]:
batch_size = 10
dataset = DataLoader(
    list(zip(train_features, train_labels)), 
    batch_size=batch_size, 
    shuffle=True
)

In [15]:
lrNet = LinearRegressor(num_inputs, True)
lrNet.initialize()
lrNet.train(dataset, epochs=5)

[epoch 1, batch 20] loss: 13.389100337028504
[epoch 1, batch 40] loss: 0.9619115110486746
[epoch 1, batch 60] loss: 0.07599612749181688
[epoch 1, batch 80] loss: 0.005195731605635956
[epoch 1, batch 100] loss: 0.0005677039429428987
[epoch 2, batch 20] loss: 0.00011957079550484195
[epoch 2, batch 40] loss: 0.00010137180165656901
[epoch 2, batch 60] loss: 9.46693553487421e-05
[epoch 2, batch 80] loss: 9.291574515373213e-05
[epoch 2, batch 100] loss: 8.235982222686289e-05
[epoch 3, batch 20] loss: 8.975042292149737e-05
[epoch 3, batch 40] loss: 9.167620683001588e-05
[epoch 3, batch 60] loss: 9.630301283323207e-05
[epoch 3, batch 80] loss: 9.094142606045353e-05
[epoch 3, batch 100] loss: 8.685547581990249e-05
[epoch 4, batch 20] loss: 7.33641514671035e-05
[epoch 4, batch 40] loss: 9.498117960902164e-05
[epoch 4, batch 60] loss: 0.00010156988973903935
[epoch 4, batch 80] loss: 9.054970596480416e-05
[epoch 4, batch 100] loss: 9.562409359205048e-05
[epoch 5, batch 20] loss: 8.219617866416229e

LinearRegressor(
  (fc1): Linear(in_features=2, out_features=1, bias=True)
  (criterion): MSELoss()
)

In [16]:
print(f"Training Loss: {lrNet.criterion(lrNet(train_features), train_labels).data:.5f}\n")
print(f"Validation Loss: {lrNet.criterion(lrNet(val_features), val_labels).data:.5f}\n")

print(f"Model Weights: \n{lrNet.fc1.weight.data}")
print(f"Model Bias: \n{lrNet.fc1.bias.data}\n")

print(f"True Weights: \n{true_w}")
print(f"True Bias: \n{true_b}\n")

Training Loss: 0.00009

Validation Loss: 0.00009

Model Weights: 
tensor([[ 2.0006, -3.3999]])
Model Bias: 
tensor([4.1998])

True Weights: 
tensor([ 2.0000, -3.4000])
True Bias: 
4.2

